# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
